name: Run Burp Suite Extension

on:
  push:
    branches:
      - main

jobs:
  run_burp_extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Burp Extension Script
        run: |
         
            java -jar "/Applications/Burp\ Suite\ Community\ Edition.app/Contents/MacOS/JavaApplicationStub" --cli -P "/Users/ashwiniraj/Documents/burp/errorResponse1.py" --extensions "/Users/ashwiniraj/Documents/burp/jython-standalone-2.7.3.jar"
