name: Use Custom Action

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Custom Action
        uses: ashwinirajm/ActionsRepo@main
        with:
          my-input: 'World'
